services:
  app:
    image: dpm_app:1.0
    container_name: dpm-app
    entrypoint: "./main"
    ports:
      - 3003:3003
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-bullseye
    container_name: dpm-postgres
    env_file:
      - ".env"
    environment:
      - POSTGRES_PASSWORD=${DPM_POSTGRES_PASSWORD}
      - POSTGRES_USER=${DPM_POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PG_DATA=/var/lib/postgresql/data
    ports:
      - "6003:6003"
    volumes:
      - postgres:/var/lib/postgresql@16.9/data
    command: -p ${DPM_POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p 6003"]
      interval: 5s
      retries: 5
      start_period: 30s
      timeout: 5s  
    restart: unless-stopped
  nginx:
    image: dpm_nginx:1.0
    container_name: dpm-nginx
    ports:
      - "80:80"
    # volumes:
    #   - ./html:/usr/share/nginx/html:ro
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres:
    driver: local