//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"dpm/internal/models"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Favor defines model for Favor.
type Favor struct {
	DurationSeconds int     `json:"duration_seconds"`
	Id              string  `json:"id"`
	Likes           int     `json:"likes"`
	MusicCover      *string `json:"music_cover,omitempty"`
	Name            string  `json:"name"`
	SongUrl         string  `json:"song_url"`
	UploaderId      string  `json:"uploader_id"`
}

// LikedTrack defines model for LikedTrack.
type LikedTrack struct {
	MusicCover       *string `json:"music_cover,omitempty"`
	MusicDuration    *int    `json:"music_duration,omitempty"`
	MusicId          *string `json:"music_id,omitempty"`
	MusicLikes       *int    `json:"music_likes,omitempty"`
	MusicName        *string `json:"music_name,omitempty"`
	SongUrl          *string `json:"song_url,omitempty"`
	UploaderId       *string `json:"uploader_id,omitempty"`
	UploaderUsername *string `json:"uploader_username,omitempty"`
}

// ListeningHistoryResponse defines model for ListeningHistoryResponse.
type ListeningHistoryResponse struct {
	ListeningDate    *time.Time `json:"listening_date,omitempty"`
	MusicCover       *string    `json:"music_cover,omitempty"`
	MusicDuration    *int       `json:"music_duration,omitempty"`
	MusicId          *string    `json:"music_id,omitempty"`
	MusicLikes       *int       `json:"music_likes,omitempty"`
	MusicName        *string    `json:"music_name,omitempty"`
	SongUrl          *string    `json:"song_url,omitempty"`
	UploaderId       *string    `json:"uploader_id,omitempty"`
	UploaderUsername *string    `json:"uploader_username,omitempty"`
}

// Music defines model for Music.
type Music struct {
	DurationSeconds int     `json:"duration_seconds"`
	Id              string  `json:"id"`
	Likes           int     `json:"likes"`
	MusicCover      *string `json:"music_cover,omitempty"`
	Name            string  `json:"name"`
	SongUrl         string  `json:"song_url"`
	UploaderId      string  `json:"uploader_id"`
}

// MusicLikes defines model for MusicLikes.
type MusicLikes struct {
	MusicId *string `json:"music_id,omitempty"`
}

// GetFavor defines model for GetFavor.
type GetFavor = []Favor

// GetLikedTracks defines model for GetLikedTracks.
type GetLikedTracks = []LikedTrack

// GetListeningHistory defines model for GetListeningHistory.
type GetListeningHistory = []ListeningHistoryResponse

// GetMusic defines model for GetMusic.
type GetMusic struct {
	Music      []Music       `json:"music"`
	MusicLikes *[]MusicLikes `json:"music_likes,omitempty"`
}

// GetMusicResponse defines model for GetMusicResponse.
type GetMusicResponse struct {
	Music      Music       `json:"music"`
	MusicFavor *MusicLikes `json:"music_favor,omitempty"`
}

// GetProfile defines model for GetProfile.
type GetProfile struct {
	Email          *string `json:"email,omitempty"`
	FavorCount     *int    `json:"favor_count,omitempty"`
	Likes          *int    `json:"likes,omitempty"`
	ListeningCount *int    `json:"listening_count,omitempty"`
	RegisterAt     *string `json:"register_at,omitempty"`
	Username       *string `json:"username,omitempty"`
}

// Login defines model for Login.
type Login struct {
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// Register defines model for Register.
type Register struct {
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// DeleteFavorJSONBody defines parameters for DeleteFavor.
type DeleteFavorJSONBody struct {
	MusicID string `json:"musicID"`
}

// DeleteFavorParams defines parameters for DeleteFavor.
type DeleteFavorParams struct {
	AccessToken string `form:"Access-Token" json:"Access-Token"`
}

// GetFavorParams defines parameters for GetFavor.
type GetFavorParams struct {
	AccessToken string `form:"Access-Token" json:"Access-Token"`
}

// AddFavorJSONBody defines parameters for AddFavor.
type AddFavorJSONBody struct {
	MusicID string `json:"musicID"`
}

// AddFavorParams defines parameters for AddFavor.
type AddFavorParams struct {
	AccessToken string `form:"Access-Token" json:"Access-Token"`
}

// GetLikesParams defines parameters for GetLikes.
type GetLikesParams struct {
	AccessToken string `form:"Access-Token" json:"Access-Token"`
}

// DeleteListeningFromLHJSONBody defines parameters for DeleteListeningFromLH.
type DeleteListeningFromLHJSONBody struct {
	ListeningDate *time.Time `json:"listening_date,omitempty"`
	MusicId       string     `json:"music_id"`
}

// DeleteListeningFromLHParams defines parameters for DeleteListeningFromLH.
type DeleteListeningFromLHParams struct {
	AccessToken string `form:"Access-Token" json:"Access-Token"`
}

// GetLHParams defines parameters for GetLH.
type GetLHParams struct {
	AccessToken string `form:"Access-Token" json:"Access-Token"`
}

// AddListeningToLHJSONBody defines parameters for AddListeningToLH.
type AddListeningToLHJSONBody struct {
	MusicID string `json:"musicID"`
}

// AddListeningToLHParams defines parameters for AddListeningToLH.
type AddListeningToLHParams struct {
	AccessToken string `form:"Access-Token" json:"Access-Token"`
}

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// PostLogoutParams defines parameters for PostLogout.
type PostLogoutParams struct {
	AccessToken        string `form:"Access-Token" json:"Access-Token"`
	RefreshTokenLogout string `form:"Refresh-Token-Logout" json:"Refresh-Token-Logout"`
}

// GetAllMusicParams defines parameters for GetAllMusic.
type GetAllMusicParams struct {
	AccessToken *string `form:"Access-Token,omitempty" json:"Access-Token,omitempty"`
}

// DeleteMusicLikeJSONBody defines parameters for DeleteMusicLike.
type DeleteMusicLikeJSONBody struct {
	MusicID *string `json:"musicID,omitempty"`
}

// DeleteMusicLikeParams defines parameters for DeleteMusicLike.
type DeleteMusicLikeParams struct {
	AccessToken string `form:"Access-Token" json:"Access-Token"`
}

// PostMusicLikeJSONBody defines parameters for PostMusicLike.
type PostMusicLikeJSONBody struct {
	MusicID *string `json:"musicID,omitempty"`
}

// PostMusicLikeParams defines parameters for PostMusicLike.
type PostMusicLikeParams struct {
	AccessToken string `form:"Access-Token" json:"Access-Token"`
}

// PostMusicPlayJSONBody defines parameters for PostMusicPlay.
type PostMusicPlayJSONBody struct {
	MusicId *string `json:"music_id,omitempty"`
}

// GetMusicParams defines parameters for GetMusic.
type GetMusicParams struct {
	AccessToken *string `form:"Access-Token,omitempty" json:"Access-Token,omitempty"`
}

// GetProfileParams defines parameters for GetProfile.
type GetProfileParams struct {
	AccessToken string `form:"Access-Token" json:"Access-Token"`
}

// RegisterJSONBody defines parameters for Register.
type RegisterJSONBody struct {
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// DeleteFavorJSONRequestBody defines body for DeleteFavor for application/json ContentType.
type DeleteFavorJSONRequestBody DeleteFavorJSONBody

// AddFavorJSONRequestBody defines body for AddFavor for application/json ContentType.
type AddFavorJSONRequestBody AddFavorJSONBody

// DeleteListeningFromLHJSONRequestBody defines body for DeleteListeningFromLH for application/json ContentType.
type DeleteListeningFromLHJSONRequestBody DeleteListeningFromLHJSONBody

// AddListeningToLHJSONRequestBody defines body for AddListeningToLH for application/json ContentType.
type AddListeningToLHJSONRequestBody AddListeningToLHJSONBody

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// DeleteMusicLikeJSONRequestBody defines body for DeleteMusicLike for application/json ContentType.
type DeleteMusicLikeJSONRequestBody DeleteMusicLikeJSONBody

// PostMusicLikeJSONRequestBody defines body for PostMusicLike for application/json ContentType.
type PostMusicLikeJSONRequestBody PostMusicLikeJSONBody

// PostMusicPlayJSONRequestBody defines body for PostMusicPlay for application/json ContentType.
type PostMusicPlayJSONRequestBody PostMusicPlayJSONBody

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody RegisterJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (DELETE /favor)
	DeleteFavor(w http.ResponseWriter, r *http.Request, params DeleteFavorParams)

	// (GET /favor)
	GetFavor(w http.ResponseWriter, r *http.Request, params GetFavorParams)

	// (POST /favor)
	AddFavor(w http.ResponseWriter, r *http.Request, params AddFavorParams)

	// (GET /likes)
	GetLikes(w http.ResponseWriter, r *http.Request, params GetLikesParams)

	// (DELETE /listening-history)
	DeleteListeningFromLH(w http.ResponseWriter, r *http.Request, params DeleteListeningFromLHParams)

	// (GET /listening-history)
	GetLH(w http.ResponseWriter, r *http.Request, params GetLHParams)

	// (POST /listening-history)
	AddListeningToLH(w http.ResponseWriter, r *http.Request, params AddListeningToLHParams)

	// (POST /login)
	Login(w http.ResponseWriter, r *http.Request)

	// (POST /logout)
	PostLogout(w http.ResponseWriter, r *http.Request, params PostLogoutParams)
	// Get all music
	// (GET /music)
	GetAllMusic(w http.ResponseWriter, r *http.Request, params GetAllMusicParams)

	// (DELETE /music/like)
	DeleteMusicLike(w http.ResponseWriter, r *http.Request, params DeleteMusicLikeParams)

	// (POST /music/like)
	PostMusicLike(w http.ResponseWriter, r *http.Request, params PostMusicLikeParams)

	// (POST /music/play)
	PostMusicPlay(w http.ResponseWriter, r *http.Request)

	// (GET /music/{musicID})
	GetMusic(w http.ResponseWriter, r *http.Request, musicID string, params GetMusicParams)

	// (GET /ping)
	GetPing(w http.ResponseWriter, r *http.Request)

	// (GET /profile)
	GetProfile(w http.ResponseWriter, r *http.Request, params GetProfileParams)

	// (POST /register)
	Register(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DeleteFavor operation middleware
func (siw *ServerInterfaceWrapper) DeleteFavor(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteFavorParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("Access-Token"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "Access-Token", cookie.Value, &value, runtime.BindStyledParameterOptions{Explode: true, Required: true})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Access-Token", Err: err})
				return
			}
			params.AccessToken = value

		} else {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "Access-Token"})
			return
		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteFavor(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFavor operation middleware
func (siw *ServerInterfaceWrapper) GetFavor(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFavorParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("Access-Token"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "Access-Token", cookie.Value, &value, runtime.BindStyledParameterOptions{Explode: true, Required: true})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Access-Token", Err: err})
				return
			}
			params.AccessToken = value

		} else {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "Access-Token"})
			return
		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFavor(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddFavor operation middleware
func (siw *ServerInterfaceWrapper) AddFavor(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params AddFavorParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("Access-Token"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "Access-Token", cookie.Value, &value, runtime.BindStyledParameterOptions{Explode: true, Required: true})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Access-Token", Err: err})
				return
			}
			params.AccessToken = value

		} else {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "Access-Token"})
			return
		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddFavor(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLikes operation middleware
func (siw *ServerInterfaceWrapper) GetLikes(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLikesParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("Access-Token"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "Access-Token", cookie.Value, &value, runtime.BindStyledParameterOptions{Explode: true, Required: true})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Access-Token", Err: err})
				return
			}
			params.AccessToken = value

		} else {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "Access-Token"})
			return
		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLikes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteListeningFromLH operation middleware
func (siw *ServerInterfaceWrapper) DeleteListeningFromLH(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteListeningFromLHParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("Access-Token"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "Access-Token", cookie.Value, &value, runtime.BindStyledParameterOptions{Explode: true, Required: true})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Access-Token", Err: err})
				return
			}
			params.AccessToken = value

		} else {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "Access-Token"})
			return
		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteListeningFromLH(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLH operation middleware
func (siw *ServerInterfaceWrapper) GetLH(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLHParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("Access-Token"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "Access-Token", cookie.Value, &value, runtime.BindStyledParameterOptions{Explode: true, Required: true})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Access-Token", Err: err})
				return
			}
			params.AccessToken = value

		} else {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "Access-Token"})
			return
		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLH(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddListeningToLH operation middleware
func (siw *ServerInterfaceWrapper) AddListeningToLH(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params AddListeningToLHParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("Access-Token"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "Access-Token", cookie.Value, &value, runtime.BindStyledParameterOptions{Explode: true, Required: true})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Access-Token", Err: err})
				return
			}
			params.AccessToken = value

		} else {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "Access-Token"})
			return
		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddListeningToLH(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostLogout operation middleware
func (siw *ServerInterfaceWrapper) PostLogout(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostLogoutParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("Access-Token"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "Access-Token", cookie.Value, &value, runtime.BindStyledParameterOptions{Explode: true, Required: true})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Access-Token", Err: err})
				return
			}
			params.AccessToken = value

		} else {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "Access-Token"})
			return
		}
	}

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("Refresh-Token-Logout"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "Refresh-Token-Logout", cookie.Value, &value, runtime.BindStyledParameterOptions{Explode: true, Required: true})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Refresh-Token-Logout", Err: err})
				return
			}
			params.RefreshTokenLogout = value

		} else {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "Refresh-Token-Logout"})
			return
		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostLogout(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAllMusic operation middleware
func (siw *ServerInterfaceWrapper) GetAllMusic(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAllMusicParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("Access-Token"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "Access-Token", cookie.Value, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Access-Token", Err: err})
				return
			}
			params.AccessToken = &value

		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAllMusic(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMusicLike operation middleware
func (siw *ServerInterfaceWrapper) DeleteMusicLike(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteMusicLikeParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("Access-Token"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "Access-Token", cookie.Value, &value, runtime.BindStyledParameterOptions{Explode: true, Required: true})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Access-Token", Err: err})
				return
			}
			params.AccessToken = value

		} else {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "Access-Token"})
			return
		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMusicLike(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostMusicLike operation middleware
func (siw *ServerInterfaceWrapper) PostMusicLike(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostMusicLikeParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("Access-Token"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "Access-Token", cookie.Value, &value, runtime.BindStyledParameterOptions{Explode: true, Required: true})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Access-Token", Err: err})
				return
			}
			params.AccessToken = value

		} else {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "Access-Token"})
			return
		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostMusicLike(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostMusicPlay operation middleware
func (siw *ServerInterfaceWrapper) PostMusicPlay(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostMusicPlay(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMusic operation middleware
func (siw *ServerInterfaceWrapper) GetMusic(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "musicID" -------------
	var musicID string

	err = runtime.BindStyledParameterWithOptions("simple", "musicID", r.PathValue("musicID"), &musicID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "musicID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMusicParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("Access-Token"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "Access-Token", cookie.Value, &value, runtime.BindStyledParameterOptions{Explode: true, Required: false})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Access-Token", Err: err})
				return
			}
			params.AccessToken = &value

		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMusic(w, r, musicID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPing operation middleware
func (siw *ServerInterfaceWrapper) GetPing(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPing(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProfile operation middleware
func (siw *ServerInterfaceWrapper) GetProfile(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetProfileParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("Access-Token"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "Access-Token", cookie.Value, &value, runtime.BindStyledParameterOptions{Explode: true, Required: true})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Access-Token", Err: err})
				return
			}
			params.AccessToken = value

		} else {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "Access-Token"})
			return
		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProfile(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("DELETE "+options.BaseURL+"/favor", wrapper.DeleteFavor)
	m.HandleFunc("GET "+options.BaseURL+"/favor", wrapper.GetFavor)
	m.HandleFunc("POST "+options.BaseURL+"/favor", wrapper.AddFavor)
	m.HandleFunc("GET "+options.BaseURL+"/likes", wrapper.GetLikes)
	m.HandleFunc("DELETE "+options.BaseURL+"/listening-history", wrapper.DeleteListeningFromLH)
	m.HandleFunc("GET "+options.BaseURL+"/listening-history", wrapper.GetLH)
	m.HandleFunc("POST "+options.BaseURL+"/listening-history", wrapper.AddListeningToLH)
	m.HandleFunc("POST "+options.BaseURL+"/login", wrapper.Login)
	m.HandleFunc("POST "+options.BaseURL+"/logout", wrapper.PostLogout)
	m.HandleFunc("GET "+options.BaseURL+"/music", wrapper.GetAllMusic)
	m.HandleFunc("DELETE "+options.BaseURL+"/music/like", wrapper.DeleteMusicLike)
	m.HandleFunc("POST "+options.BaseURL+"/music/like", wrapper.PostMusicLike)
	m.HandleFunc("POST "+options.BaseURL+"/music/play", wrapper.PostMusicPlay)
	m.HandleFunc("GET "+options.BaseURL+"/music/{musicID}", wrapper.GetMusic)
	m.HandleFunc("GET "+options.BaseURL+"/ping", wrapper.GetPing)
	m.HandleFunc("GET "+options.BaseURL+"/profile", wrapper.GetProfile)
	m.HandleFunc("POST "+options.BaseURL+"/register", wrapper.Register)

	return m
}

type GetFavorJSONResponse []Favor

type GetLikedTracksJSONResponse []LikedTrack

type GetListeningHistoryJSONResponse []ListeningHistoryResponse

type GetMusicJSONResponse struct {
	Music      []Music       `json:"music"`
	MusicLikes *[]MusicLikes `json:"music_likes,omitempty"`
}

type GetMusicResponseJSONResponse struct {
	Music      Music       `json:"music"`
	MusicFavor *MusicLikes `json:"music_favor,omitempty"`
}

type GetProfileJSONResponse struct {
	Email          *string `json:"email,omitempty"`
	FavorCount     *int    `json:"favor_count,omitempty"`
	Likes          *int    `json:"likes,omitempty"`
	ListeningCount *int    `json:"listening_count,omitempty"`
	RegisterAt     *string `json:"register_at,omitempty"`
	Username       *string `json:"username,omitempty"`
}

type DeleteFavorRequestObject struct {
	Params DeleteFavorParams
	Body   *DeleteFavorJSONRequestBody
}

type DeleteFavorResponseObject interface {
	VisitDeleteFavorResponse(w http.ResponseWriter) error
}

type DeleteFavor200JSONResponse string

func (response DeleteFavor200JSONResponse) VisitDeleteFavorResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteFavor500JSONResponse string

func (response DeleteFavor500JSONResponse) VisitDeleteFavorResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetFavorRequestObject struct {
	Params GetFavorParams
}

type GetFavorResponseObject interface {
	VisitGetFavorResponse(w http.ResponseWriter) error
}

type GetFavor200JSONResponse struct{ GetFavorJSONResponse }

func (response GetFavor200JSONResponse) VisitGetFavorResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetFavor500JSONResponse string

func (response GetFavor500JSONResponse) VisitGetFavorResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AddFavorRequestObject struct {
	Params AddFavorParams
	Body   *AddFavorJSONRequestBody
}

type AddFavorResponseObject interface {
	VisitAddFavorResponse(w http.ResponseWriter) error
}

type AddFavor200JSONResponse string

func (response AddFavor200JSONResponse) VisitAddFavorResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AddFavor500JSONResponse string

func (response AddFavor500JSONResponse) VisitAddFavorResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetLikesRequestObject struct {
	Params GetLikesParams
}

type GetLikesResponseObject interface {
	VisitGetLikesResponse(w http.ResponseWriter) error
}

type GetLikes200JSONResponse struct{ GetLikedTracksJSONResponse }

func (response GetLikes200JSONResponse) VisitGetLikesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLikes500JSONResponse string

func (response GetLikes500JSONResponse) VisitGetLikesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteListeningFromLHRequestObject struct {
	Params DeleteListeningFromLHParams
	Body   *DeleteListeningFromLHJSONRequestBody
}

type DeleteListeningFromLHResponseObject interface {
	VisitDeleteListeningFromLHResponse(w http.ResponseWriter) error
}

type DeleteListeningFromLH200JSONResponse string

func (response DeleteListeningFromLH200JSONResponse) VisitDeleteListeningFromLHResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteListeningFromLH500JSONResponse string

func (response DeleteListeningFromLH500JSONResponse) VisitDeleteListeningFromLHResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetLHRequestObject struct {
	Params GetLHParams
}

type GetLHResponseObject interface {
	VisitGetLHResponse(w http.ResponseWriter) error
}

type GetLH200JSONResponse struct {
	GetListeningHistoryJSONResponse
}

func (response GetLH200JSONResponse) VisitGetLHResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLH500JSONResponse string

func (response GetLH500JSONResponse) VisitGetLHResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AddListeningToLHRequestObject struct {
	Params AddListeningToLHParams
	Body   *AddListeningToLHJSONRequestBody
}

type AddListeningToLHResponseObject interface {
	VisitAddListeningToLHResponse(w http.ResponseWriter) error
}

type AddListeningToLH200JSONResponse string

func (response AddListeningToLH200JSONResponse) VisitAddListeningToLHResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AddListeningToLH500JSONResponse string

func (response AddListeningToLH500JSONResponse) VisitAddListeningToLHResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200ResponseHeaders struct {
	AccessToken  interface{}
	RefreshToken interface{}
}

type Login200JSONResponse struct {
	Body struct {
		Message *string `json:"message,omitempty"`
	}
	Headers Login200ResponseHeaders
}

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	slog.Info("Login200Response")
	access, ok := response.Headers.AccessToken.(models.JWTAccess)
	if !ok {
		slog.Error("not access")
	}
	slog.Info(access.Sign)
	refresh, ok := response.Headers.RefreshToken.(models.JWTRefresh)
	if !ok {
		slog.Error("not refresh")
	}

	http.SetCookie(w, &http.Cookie{
		Name:     "Access-Token",
		Value:    access.Sign,
		Expires:  time.Now().Add(time.Hour * 1),
		Secure:   true,
		Path:     "/",
		HttpOnly: true,
		SameSite: http.SameSiteNoneMode,
		Domain:   "",
	})
	http.SetCookie(w, &http.Cookie{
		Name:     "Refresh-Token",
		Value:    refresh.Sign,
		Expires:  time.Now().Add(time.Hour * 24),
		Secure:   true,
		HttpOnly: true,
		Domain:   "",
		Path:     "/refresh",
		SameSite: http.SameSiteNoneMode,
	})
	http.SetCookie(w, &http.Cookie{
		Name:     "Refresh-Token-Logout",
		Value:    refresh.Sign,
		Expires:  time.Now().Add(time.Hour * 24),
		Secure:   true,
		HttpOnly: true,
		Domain:   "",
		Path:     "/logout",
		SameSite: http.SameSiteNoneMode,
	})

	w.WriteHeader(200)

	return nil
}

type Login500JSONResponse struct {
	Message *string `json:"message,omitempty"`
}

func (response Login500JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostLogoutRequestObject struct {
	Params PostLogoutParams
}

type PostLogoutResponseObject interface {
	VisitPostLogoutResponse(w http.ResponseWriter) error
}

type PostLogout200ResponseHeaders struct {
	AccessToken        interface{}
	RefreshTokenLogout interface{}
}

type PostLogout200Response struct {
	Headers PostLogout200ResponseHeaders
}

func (response PostLogout200Response) VisitPostLogoutResponse(w http.ResponseWriter) error {
	slog.Info("Logout200Response")
	access, ok := response.Headers.AccessToken.(models.JWTAccess)
	if !ok {
		slog.Error("not access")
	}
	slog.Info(access.Sign)
	refresh, ok := response.Headers.RefreshTokenLogout.(models.JWTRefresh)
	if !ok {
		slog.Error("not refresh")
	}
	_ = refresh

	http.SetCookie(w, &http.Cookie{
		Name:     "Access-Token",
		Value:    "",
		Expires:  time.Now().Add(time.Second * 5),
		Secure:   true,
		Path:     "/",
		HttpOnly: true,
		SameSite: http.SameSiteNoneMode,
		Domain:   "",
	})
	http.SetCookie(w, &http.Cookie{
		Name:     "Refresh-Token",
		Value:    "",
		Expires:  time.Now().Add(time.Second * 5),
		Secure:   true,
		HttpOnly: true,
		Domain:   "",
		Path:     "/refresh",
		SameSite: http.SameSiteNoneMode,
	})
	http.SetCookie(w, &http.Cookie{
		Name:     "Refresh-Token-Logout",
		Value:    "",
		Expires:  time.Now().Add(time.Second * 5),
		Secure:   true,
		HttpOnly: true,
		Domain:   "",
		Path:     "/logout",
		SameSite: http.SameSiteNoneMode,
	})

	w.WriteHeader(200)

	return nil
}

type PostLogout500JSONResponse string

func (response PostLogout500JSONResponse) VisitPostLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAllMusicRequestObject struct {
	Params GetAllMusicParams
}

type GetAllMusicResponseObject interface {
	VisitGetAllMusicResponse(w http.ResponseWriter) error
}

type GetAllMusic200JSONResponse struct{ GetMusicJSONResponse }

func (response GetAllMusic200JSONResponse) VisitGetAllMusicResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAllMusic500JSONResponse string

func (response GetAllMusic500JSONResponse) VisitGetAllMusicResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteMusicLikeRequestObject struct {
	Params DeleteMusicLikeParams
	Body   *DeleteMusicLikeJSONRequestBody
}

type DeleteMusicLikeResponseObject interface {
	VisitDeleteMusicLikeResponse(w http.ResponseWriter) error
}

type DeleteMusicLike200JSONResponse string

func (response DeleteMusicLike200JSONResponse) VisitDeleteMusicLikeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteMusicLike500JSONResponse string

func (response DeleteMusicLike500JSONResponse) VisitDeleteMusicLikeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostMusicLikeRequestObject struct {
	Params PostMusicLikeParams
	Body   *PostMusicLikeJSONRequestBody
}

type PostMusicLikeResponseObject interface {
	VisitPostMusicLikeResponse(w http.ResponseWriter) error
}

type PostMusicLike200JSONResponse string

func (response PostMusicLike200JSONResponse) VisitPostMusicLikeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostMusicLike500JSONResponse string

func (response PostMusicLike500JSONResponse) VisitPostMusicLikeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostMusicPlayRequestObject struct {
	Body *PostMusicPlayJSONRequestBody
}

type PostMusicPlayResponseObject interface {
	VisitPostMusicPlayResponse(w http.ResponseWriter) error
}

type PostMusicPlay200JSONResponse struct {
	PresignUrl *string `json:"presign_url,omitempty"`
}

func (response PostMusicPlay200JSONResponse) VisitPostMusicPlayResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostMusicPlay500JSONResponse string

func (response PostMusicPlay500JSONResponse) VisitPostMusicPlayResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetMusicRequestObject struct {
	MusicID string `json:"musicID"`
	Params  GetMusicParams
}

type GetMusicResponseObject interface {
	VisitGetMusicResponse(w http.ResponseWriter) error
}

type GetMusic200JSONResponse struct{ GetMusicResponseJSONResponse }

func (response GetMusic200JSONResponse) VisitGetMusicResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMusic500JSONResponse struct {
	Message *string `json:"message,omitempty"`
}

func (response GetMusic500JSONResponse) VisitGetMusicResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetPingRequestObject struct {
}

type GetPingResponseObject interface {
	VisitGetPingResponse(w http.ResponseWriter) error
}

type GetPing200JSONResponse string

func (response GetPing200JSONResponse) VisitGetPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPing500JSONResponse string

func (response GetPing500JSONResponse) VisitGetPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetProfileRequestObject struct {
	Params GetProfileParams
}

type GetProfileResponseObject interface {
	VisitGetProfileResponse(w http.ResponseWriter) error
}

type GetProfile200JSONResponse struct{ GetProfileJSONResponse }

func (response GetProfile200JSONResponse) VisitGetProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProfile500JSONResponse string

func (response GetProfile500JSONResponse) VisitGetProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RegisterRequestObject struct {
	Body *RegisterJSONRequestBody
}

type RegisterResponseObject interface {
	VisitRegisterResponse(w http.ResponseWriter) error
}

type Register200JSONResponse struct {
	Message *string `json:"message,omitempty"`
}

func (response Register200JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Register500JSONResponse struct {
	Message *string `json:"message,omitempty"`
}

func (response Register500JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (DELETE /favor)
	DeleteFavor(ctx context.Context, request DeleteFavorRequestObject) (DeleteFavorResponseObject, error)

	// (GET /favor)
	GetFavor(ctx context.Context, request GetFavorRequestObject) (GetFavorResponseObject, error)

	// (POST /favor)
	AddFavor(ctx context.Context, request AddFavorRequestObject) (AddFavorResponseObject, error)

	// (GET /likes)
	GetLikes(ctx context.Context, request GetLikesRequestObject) (GetLikesResponseObject, error)

	// (DELETE /listening-history)
	DeleteListeningFromLH(ctx context.Context, request DeleteListeningFromLHRequestObject) (DeleteListeningFromLHResponseObject, error)

	// (GET /listening-history)
	GetLH(ctx context.Context, request GetLHRequestObject) (GetLHResponseObject, error)

	// (POST /listening-history)
	AddListeningToLH(ctx context.Context, request AddListeningToLHRequestObject) (AddListeningToLHResponseObject, error)

	// (POST /login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)

	// (POST /logout)
	PostLogout(ctx context.Context, request PostLogoutRequestObject) (PostLogoutResponseObject, error)
	// Get all music
	// (GET /music)
	GetAllMusic(ctx context.Context, request GetAllMusicRequestObject) (GetAllMusicResponseObject, error)

	// (DELETE /music/like)
	DeleteMusicLike(ctx context.Context, request DeleteMusicLikeRequestObject) (DeleteMusicLikeResponseObject, error)

	// (POST /music/like)
	PostMusicLike(ctx context.Context, request PostMusicLikeRequestObject) (PostMusicLikeResponseObject, error)

	// (POST /music/play)
	PostMusicPlay(ctx context.Context, request PostMusicPlayRequestObject) (PostMusicPlayResponseObject, error)

	// (GET /music/{musicID})
	GetMusic(ctx context.Context, request GetMusicRequestObject) (GetMusicResponseObject, error)

	// (GET /ping)
	GetPing(ctx context.Context, request GetPingRequestObject) (GetPingResponseObject, error)

	// (GET /profile)
	GetProfile(ctx context.Context, request GetProfileRequestObject) (GetProfileResponseObject, error)

	// (POST /register)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// DeleteFavor operation middleware
func (sh *strictHandler) DeleteFavor(w http.ResponseWriter, r *http.Request, params DeleteFavorParams) {
	var request DeleteFavorRequestObject

	request.Params = params

	var body DeleteFavorJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteFavor(ctx, request.(DeleteFavorRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteFavor")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteFavorResponseObject); ok {
		if err := validResponse.VisitDeleteFavorResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFavor operation middleware
func (sh *strictHandler) GetFavor(w http.ResponseWriter, r *http.Request, params GetFavorParams) {
	var request GetFavorRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetFavor(ctx, request.(GetFavorRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFavor")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetFavorResponseObject); ok {
		if err := validResponse.VisitGetFavorResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddFavor operation middleware
func (sh *strictHandler) AddFavor(w http.ResponseWriter, r *http.Request, params AddFavorParams) {
	var request AddFavorRequestObject

	request.Params = params

	var body AddFavorJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddFavor(ctx, request.(AddFavorRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddFavor")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddFavorResponseObject); ok {
		if err := validResponse.VisitAddFavorResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLikes operation middleware
func (sh *strictHandler) GetLikes(w http.ResponseWriter, r *http.Request, params GetLikesParams) {
	var request GetLikesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLikes(ctx, request.(GetLikesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLikes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLikesResponseObject); ok {
		if err := validResponse.VisitGetLikesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteListeningFromLH operation middleware
func (sh *strictHandler) DeleteListeningFromLH(w http.ResponseWriter, r *http.Request, params DeleteListeningFromLHParams) {
	var request DeleteListeningFromLHRequestObject

	request.Params = params

	var body DeleteListeningFromLHJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteListeningFromLH(ctx, request.(DeleteListeningFromLHRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteListeningFromLH")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteListeningFromLHResponseObject); ok {
		if err := validResponse.VisitDeleteListeningFromLHResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLH operation middleware
func (sh *strictHandler) GetLH(w http.ResponseWriter, r *http.Request, params GetLHParams) {
	var request GetLHRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLH(ctx, request.(GetLHRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLH")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLHResponseObject); ok {
		if err := validResponse.VisitGetLHResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddListeningToLH operation middleware
func (sh *strictHandler) AddListeningToLH(w http.ResponseWriter, r *http.Request, params AddListeningToLHParams) {
	var request AddListeningToLHRequestObject

	request.Params = params

	var body AddListeningToLHJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddListeningToLH(ctx, request.(AddListeningToLHRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddListeningToLH")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddListeningToLHResponseObject); ok {
		if err := validResponse.VisitAddListeningToLHResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostLogout operation middleware
func (sh *strictHandler) PostLogout(w http.ResponseWriter, r *http.Request, params PostLogoutParams) {
	var request PostLogoutRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostLogout(ctx, request.(PostLogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostLogout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostLogoutResponseObject); ok {
		if err := validResponse.VisitPostLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAllMusic operation middleware
func (sh *strictHandler) GetAllMusic(w http.ResponseWriter, r *http.Request, params GetAllMusicParams) {
	var request GetAllMusicRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAllMusic(ctx, request.(GetAllMusicRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAllMusic")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAllMusicResponseObject); ok {
		if err := validResponse.VisitGetAllMusicResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteMusicLike operation middleware
func (sh *strictHandler) DeleteMusicLike(w http.ResponseWriter, r *http.Request, params DeleteMusicLikeParams) {
	var request DeleteMusicLikeRequestObject

	request.Params = params

	var body DeleteMusicLikeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteMusicLike(ctx, request.(DeleteMusicLikeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteMusicLike")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteMusicLikeResponseObject); ok {
		if err := validResponse.VisitDeleteMusicLikeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostMusicLike operation middleware
func (sh *strictHandler) PostMusicLike(w http.ResponseWriter, r *http.Request, params PostMusicLikeParams) {
	var request PostMusicLikeRequestObject

	request.Params = params

	var body PostMusicLikeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostMusicLike(ctx, request.(PostMusicLikeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostMusicLike")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostMusicLikeResponseObject); ok {
		if err := validResponse.VisitPostMusicLikeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostMusicPlay operation middleware
func (sh *strictHandler) PostMusicPlay(w http.ResponseWriter, r *http.Request) {
	var request PostMusicPlayRequestObject

	var body PostMusicPlayJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostMusicPlay(ctx, request.(PostMusicPlayRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostMusicPlay")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostMusicPlayResponseObject); ok {
		if err := validResponse.VisitPostMusicPlayResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMusic operation middleware
func (sh *strictHandler) GetMusic(w http.ResponseWriter, r *http.Request, musicID string, params GetMusicParams) {
	var request GetMusicRequestObject

	request.MusicID = musicID
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMusic(ctx, request.(GetMusicRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMusic")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMusicResponseObject); ok {
		if err := validResponse.VisitGetMusicResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPing operation middleware
func (sh *strictHandler) GetPing(w http.ResponseWriter, r *http.Request) {
	var request GetPingRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPing(ctx, request.(GetPingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPing")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPingResponseObject); ok {
		if err := validResponse.VisitGetPingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProfile operation middleware
func (sh *strictHandler) GetProfile(w http.ResponseWriter, r *http.Request, params GetProfileParams) {
	var request GetProfileRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProfile(ctx, request.(GetProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProfile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProfileResponseObject); ok {
		if err := validResponse.VisitGetProfileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Register operation middleware
func (sh *strictHandler) Register(w http.ResponseWriter, r *http.Request) {
	var request RegisterRequestObject

	var body RegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Register(ctx, request.(RegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Register")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterResponseObject); ok {
		if err := validResponse.VisitRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaT2/buBL/KgTfA3pRovQVvfj0vJu2CeBig2x6KoqAkcYWG0lkSSqBEfi7L0iKlGxR",
	"thzbWafIzdaQo+Fv/nP0hBNWcFZCqSQePeEMSArC/BwnCUh5w+6h1H8TVioolf5JOM9pQhRlZfxTMkOW",
	"SQYF0b/UnAMeYakELWd4sVgsInwNUwEy2wezRYQF/KpAqj9YSsGIOmEzuh1fLhgHoer9nEj5yEQaeGOE",
	"KwmiJAWExLGyUAEpHn33K5Hn9yNyW9jdT0gUNvKnIBNBuRYNj/A1/EJ3LJ2jKRMozs1RDGQzKhWIHY4F",
	"BaF58EyHOjCyr9z+2MKd1r5CclZKe4gvoD6TB7YdDlRBYXb/V8AUj/B/4sbMY7tMxpbtwstKhCDzkKhf",
	"Pt2geOpWfwE1ofeQ3giS3Mv9i9UwHyxbTu9BetmkgpKWswsqFRPzQwi4/IbrWl2DxAWFcrcfZbWIVvKv",
	"laTJDuZeuP2DTmHf1hE5smxuLaRbMZs4LayAsOwzVsohHqKxInmOCiepw8gDvgesBkFkIZk6NxyKxLNP",
	"/pehIJURhR5pnqM7QAJUJUpI0d0cxVywtEpU/FT/uDxfIO0J+ogGgBquK8GmNIeDxFADx23CKsu0ptNS",
	"wQxMoPAmFCLVLrBuv4uJt0Q9I05vNi8dOXgNkCbXKtTsfMRdBiOtLLq3EhJWpj2Ho+G0sgYOa18Je7Dp",
	"rrO155QRlqyc3VYirKCK50xXM7dBgVaMk6a4fs/yRid31D18hK3ELTG6xh3hVjwPu+Gag1u6e/M68HpA",
	"XwlmfbsPAXCLvpWlasR6EkwHv8aPUqIMfcpEof0F6wcnihqF9sDyhvsy7j4Bv3n9zl7fyoM9Xt8nXyBw",
	"03LKXA4jiWrlJVxUCrhgeu3/Z/rZacIKd6gR/lopQDUdd1KAERIVNBFMgnigCaCLm5srNL66NGX50u4I",
	"K6pyCG7DEX4AIS3X96dnp2f6ZYxDSTjFI/zh9Oz0PdZ9h8oMBLEvJlLIwbrusmzn5rktfpBiSNvyO4ns",
	"PsPbKuYy9Ys/1zROBClAmT72+xPWrSFOGLun0ABju9sT25G2jUKJCqI1HeiPdv8537UEuzzfbKRuYahy",
	"Wu2W/nd2tlt/vWoif1cGKK3Oj3vnDeIBBAIhdGfVpY8T/UOiR6qyVf3PQHVtRlfMa+3EN5MvYSRdtYQK",
	"Z78u9sK9DNacyQCE4zQd6HPjNH1zuNftcIsIxz5Bb/Y9lxM3+Z5b1/G9SU04St9rX+ocBvwA9nX5epI1",
	"lzUbEmJzezIVrAhcpoRzo6+pPwtWTC5ejdPuVuEPqQH9yrf8any3a0+9/r7Z+LRfXRyvx69clR5H4qXl",
	"AGDHaerFv2GvyKHfsnAwC7sJVtg4vkkQSJO0PSA/diFl2oxe9J8ZKKS0bk37RiqVQalqUTsmZKdmHb2G",
	"3aY1cYsnbka1kw5WzAKkJLPn3mU6dUXdAeaJHzqGDlYvj9vDzmZeOWzv0nDTCPfx34SiE29kVRRE1xZW",
	"4zq+PMId4RzXlseqgMlNzHNbZMi5VFDgvtBll3bs64pJ5UkHDU5RD8MlNZ54WXbOLC9ofE7qg9vgxrD1",
	"qR2v/Pyorg06WX+c5/Y68Vmq33+u97OsQ4fztr91JngNaZwoW3d5msXU9GMD2oBWq4VYWXMJl/7+KvL3",
	"qBF+r2Lg0/rivNN/t5UdjsY67A4zD73yzTheg3E04YHnZB7QeU7mm8zCL4mQtCGLlPJR15UCJC1n364n",
	"SDFU8A/IjIR7rUVzwnvV5vBZyH6LTnPyWdkzS9qm8HypPsEagR1VBdoE87yTUp5ql1m0Ena3mbfN590c",
	"XZ6H2viebL7Mx/IwDEz04ERlTexwnruP0u5lCob2p03HWtS3EwUroaV9rvmvqdGuNP33uuBqYPkzg+Qe",
	"ZUBylSE3pjSoNN8EdZvsdxI5+uZ77mZlF1pPOsqbLyfewZOWaH3Fus3VRmS/JI2WrzcI58hxRBktdCvr",
	"e9NlHfjPZ59xv+H3HuMVxxFHIodb+4ZhsfgnAAD//wncwz5jLgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
