//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"dpm/internal/models"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// ListeningHistoryResponse defines model for ListeningHistoryResponse.
type ListeningHistoryResponse struct {
	ListeningDate    *time.Time `json:"listening_date,omitempty"`
	MusicCover       *string    `json:"music_cover,omitempty"`
	MusicDuration    *int       `json:"music_duration,omitempty"`
	MusicId          *string    `json:"music_id,omitempty"`
	MusicLikes       *int       `json:"music_likes,omitempty"`
	MusicName        *string    `json:"music_name,omitempty"`
	SongUrl          *string    `json:"song_url,omitempty"`
	UploaderId       *string    `json:"uploader_id,omitempty"`
	UploaderUsername *string    `json:"uploader_username,omitempty"`
}

// Music defines model for Music.
type Music struct {
	DurationSeconds int     `json:"duration_seconds"`
	Id              string  `json:"id"`
	Likes           int     `json:"likes"`
	MusicCover      *string `json:"music_cover,omitempty"`
	Name            string  `json:"name"`
	SongUrl         string  `json:"song_url"`
	UploaderId      string  `json:"uploader_id"`
}

// GetListeningHistory defines model for GetListeningHistory.
type GetListeningHistory = []ListeningHistoryResponse

// GetMusic defines model for GetMusic.
type GetMusic = []Music

// GetMusicResponse defines model for GetMusicResponse.
type GetMusicResponse struct {
	DurationSeconds *int    `json:"duration_seconds,omitempty"`
	Id              *string `json:"id,omitempty"`
	Likes           *int    `json:"likes,omitempty"`
	MusicCover      *string `json:"music_cover,omitempty"`
	Name            *string `json:"name,omitempty"`
	SongUrl         *string `json:"song_url,omitempty"`
	UploaderId      *string `json:"uploader_id,omitempty"`
}

// Login defines model for Login.
type Login struct {
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// Register defines model for Register.
type Register struct {
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// DeleteListeningFromLHJSONBody defines parameters for DeleteListeningFromLH.
type DeleteListeningFromLHJSONBody struct {
	MusicId string `json:"music_id"`
}

// AddListeningToLHJSONBody defines parameters for AddListeningToLH.
type AddListeningToLHJSONBody struct {
	MusicID string `json:"musicID"`
}

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// RegisterJSONBody defines parameters for Register.
type RegisterJSONBody struct {
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// DeleteListeningFromLHJSONRequestBody defines body for DeleteListeningFromLH for application/json ContentType.
type DeleteListeningFromLHJSONRequestBody DeleteListeningFromLHJSONBody

// AddListeningToLHJSONRequestBody defines body for AddListeningToLH for application/json ContentType.
type AddListeningToLHJSONRequestBody AddListeningToLHJSONBody

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody RegisterJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (DELETE /listening-history/{userID})
	DeleteListeningFromLH(w http.ResponseWriter, r *http.Request, userID string)

	// (GET /listening-history/{userID})
	GetLH(w http.ResponseWriter, r *http.Request, userID string)

	// (POST /listening-history/{userID})
	AddListeningToLH(w http.ResponseWriter, r *http.Request, userID string)

	// (POST /login)
	Login(w http.ResponseWriter, r *http.Request)
	// Get all music
	// (GET /music)
	GetAllMusic(w http.ResponseWriter, r *http.Request)

	// (GET /music/{musicID})
	GetMusic(w http.ResponseWriter, r *http.Request, musicID string)

	// (GET /ping)
	GetPing(w http.ResponseWriter, r *http.Request)

	// (POST /register)
	Register(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DeleteListeningFromLH operation middleware
func (siw *ServerInterfaceWrapper) DeleteListeningFromLH(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID string

	err = runtime.BindStyledParameterWithOptions("simple", "userID", r.PathValue("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteListeningFromLH(w, r, userID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLH operation middleware
func (siw *ServerInterfaceWrapper) GetLH(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID string

	err = runtime.BindStyledParameterWithOptions("simple", "userID", r.PathValue("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLH(w, r, userID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddListeningToLH operation middleware
func (siw *ServerInterfaceWrapper) AddListeningToLH(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID string

	err = runtime.BindStyledParameterWithOptions("simple", "userID", r.PathValue("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddListeningToLH(w, r, userID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAllMusic operation middleware
func (siw *ServerInterfaceWrapper) GetAllMusic(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAllMusic(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMusic operation middleware
func (siw *ServerInterfaceWrapper) GetMusic(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "musicID" -------------
	var musicID string

	err = runtime.BindStyledParameterWithOptions("simple", "musicID", r.PathValue("musicID"), &musicID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "musicID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMusic(w, r, musicID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPing operation middleware
func (siw *ServerInterfaceWrapper) GetPing(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPing(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("DELETE "+options.BaseURL+"/listening-history/{userID}", wrapper.DeleteListeningFromLH)
	m.HandleFunc("GET "+options.BaseURL+"/listening-history/{userID}", wrapper.GetLH)
	m.HandleFunc("POST "+options.BaseURL+"/listening-history/{userID}", wrapper.AddListeningToLH)
	m.HandleFunc("POST "+options.BaseURL+"/login", wrapper.Login)
	m.HandleFunc("GET "+options.BaseURL+"/music", wrapper.GetAllMusic)
	m.HandleFunc("GET "+options.BaseURL+"/music/{musicID}", wrapper.GetMusic)
	m.HandleFunc("GET "+options.BaseURL+"/ping", wrapper.GetPing)
	m.HandleFunc("POST "+options.BaseURL+"/register", wrapper.Register)

	return m
}

type GetListeningHistoryJSONResponse []ListeningHistoryResponse

type GetMusicJSONResponse []Music

type GetMusicResponseJSONResponse struct {
	DurationSeconds *int    `json:"duration_seconds,omitempty"`
	Id              *string `json:"id,omitempty"`
	Likes           *int    `json:"likes,omitempty"`
	MusicCover      *string `json:"music_cover,omitempty"`
	Name            *string `json:"name,omitempty"`
	SongUrl         *string `json:"song_url,omitempty"`
	UploaderId      *string `json:"uploader_id,omitempty"`
}

type DeleteListeningFromLHRequestObject struct {
	UserID string `json:"userID"`
	Body   *DeleteListeningFromLHJSONRequestBody
}

type DeleteListeningFromLHResponseObject interface {
	VisitDeleteListeningFromLHResponse(w http.ResponseWriter) error
}

type DeleteListeningFromLH200JSONResponse string

func (response DeleteListeningFromLH200JSONResponse) VisitDeleteListeningFromLHResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteListeningFromLH500JSONResponse string

func (response DeleteListeningFromLH500JSONResponse) VisitDeleteListeningFromLHResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetLHRequestObject struct {
	UserID string `json:"userID"`
}

type GetLHResponseObject interface {
	VisitGetLHResponse(w http.ResponseWriter) error
}

type GetLH200JSONResponse struct {
	GetListeningHistoryJSONResponse
}

func (response GetLH200JSONResponse) VisitGetLHResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLH500JSONResponse string

func (response GetLH500JSONResponse) VisitGetLHResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AddListeningToLHRequestObject struct {
	UserID string `json:"userID"`
	Body   *AddListeningToLHJSONRequestBody
}

type AddListeningToLHResponseObject interface {
	VisitAddListeningToLHResponse(w http.ResponseWriter) error
}

type AddListeningToLH200JSONResponse string

func (response AddListeningToLH200JSONResponse) VisitAddListeningToLHResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AddListeningToLH500JSONResponse string

func (response AddListeningToLH500JSONResponse) VisitAddListeningToLHResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200ResponseHeaders struct {
	AccessToken  interface{}
	RefreshToken interface{}
}

type Login200JSONResponse struct {
	Body struct {
		Message *string `json:"message,omitempty"`
	}
	Headers Login200ResponseHeaders
}

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	access, ok := response.Headers.AccessToken.(models.JWTAccess)
	if !ok {
		slog.Error("not access")
	}
	refresh, ok := response.Headers.RefreshToken.(models.JWTRefresh)
	if !ok {
		slog.Error("not refresh")
	}

	http.SetCookie(w, &http.Cookie{
		Name: "Access-Token",
		Value: access.Sign,
		Expires: time.Now().Add(time.Hour * 12),
		Secure: true,
		HttpOnly: true,
	})
	http.SetCookie(w, &http.Cookie{
		Name: "Refresh-Token",
		Value: refresh.Sign,
		Expires: time.Now().Add(time.Hour * 48),
		Secure: true,
		HttpOnly: true,
		Path: "/refresh",
	})

	w.WriteHeader(200)

	return nil
}
type Login500JSONResponse struct {
	Message *string `json:"message,omitempty"`
}

func (response Login500JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAllMusicRequestObject struct {
}

type GetAllMusicResponseObject interface {
	VisitGetAllMusicResponse(w http.ResponseWriter) error
}

type GetAllMusic200JSONResponse struct{ GetMusicJSONResponse }

func (response GetAllMusic200JSONResponse) VisitGetAllMusicResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAllMusic500JSONResponse string

func (response GetAllMusic500JSONResponse) VisitGetAllMusicResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetMusicRequestObject struct {
	MusicID string `json:"musicID"`
}

type GetMusicResponseObject interface {
	VisitGetMusicResponse(w http.ResponseWriter) error
}

type GetMusic200JSONResponse struct{ GetMusicResponseJSONResponse }

func (response GetMusic200JSONResponse) VisitGetMusicResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMusic500JSONResponse struct {
	Message *string `json:"message,omitempty"`
}

func (response GetMusic500JSONResponse) VisitGetMusicResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetPingRequestObject struct {
}

type GetPingResponseObject interface {
	VisitGetPingResponse(w http.ResponseWriter) error
}

type GetPing200JSONResponse string

func (response GetPing200JSONResponse) VisitGetPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPing500JSONResponse string

func (response GetPing500JSONResponse) VisitGetPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RegisterRequestObject struct {
	Body *RegisterJSONRequestBody
}

type RegisterResponseObject interface {
	VisitRegisterResponse(w http.ResponseWriter) error
}

type Register200JSONResponse struct {
	Message *string `json:"message,omitempty"`
}

func (response Register200JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Register500JSONResponse struct {
	Message *string `json:"message,omitempty"`
}

func (response Register500JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (DELETE /listening-history/{userID})
	DeleteListeningFromLH(ctx context.Context, request DeleteListeningFromLHRequestObject) (DeleteListeningFromLHResponseObject, error)

	// (GET /listening-history/{userID})
	GetLH(ctx context.Context, request GetLHRequestObject) (GetLHResponseObject, error)

	// (POST /listening-history/{userID})
	AddListeningToLH(ctx context.Context, request AddListeningToLHRequestObject) (AddListeningToLHResponseObject, error)

	// (POST /login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Get all music
	// (GET /music)
	GetAllMusic(ctx context.Context, request GetAllMusicRequestObject) (GetAllMusicResponseObject, error)

	// (GET /music/{musicID})
	GetMusic(ctx context.Context, request GetMusicRequestObject) (GetMusicResponseObject, error)

	// (GET /ping)
	GetPing(ctx context.Context, request GetPingRequestObject) (GetPingResponseObject, error)

	// (POST /register)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// DeleteListeningFromLH operation middleware
func (sh *strictHandler) DeleteListeningFromLH(w http.ResponseWriter, r *http.Request, userID string) {
	var request DeleteListeningFromLHRequestObject

	request.UserID = userID

	var body DeleteListeningFromLHJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteListeningFromLH(ctx, request.(DeleteListeningFromLHRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteListeningFromLH")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteListeningFromLHResponseObject); ok {
		if err := validResponse.VisitDeleteListeningFromLHResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLH operation middleware
func (sh *strictHandler) GetLH(w http.ResponseWriter, r *http.Request, userID string) {
	var request GetLHRequestObject

	request.UserID = userID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLH(ctx, request.(GetLHRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLH")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLHResponseObject); ok {
		if err := validResponse.VisitGetLHResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddListeningToLH operation middleware
func (sh *strictHandler) AddListeningToLH(w http.ResponseWriter, r *http.Request, userID string) {
	var request AddListeningToLHRequestObject

	request.UserID = userID

	var body AddListeningToLHJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddListeningToLH(ctx, request.(AddListeningToLHRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddListeningToLH")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddListeningToLHResponseObject); ok {
		if err := validResponse.VisitAddListeningToLHResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAllMusic operation middleware
func (sh *strictHandler) GetAllMusic(w http.ResponseWriter, r *http.Request) {
	var request GetAllMusicRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAllMusic(ctx, request.(GetAllMusicRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAllMusic")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAllMusicResponseObject); ok {
		if err := validResponse.VisitGetAllMusicResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMusic operation middleware
func (sh *strictHandler) GetMusic(w http.ResponseWriter, r *http.Request, musicID string) {
	var request GetMusicRequestObject

	request.MusicID = musicID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMusic(ctx, request.(GetMusicRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMusic")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMusicResponseObject); ok {
		if err := validResponse.VisitGetMusicResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPing operation middleware
func (sh *strictHandler) GetPing(w http.ResponseWriter, r *http.Request) {
	var request GetPingRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPing(ctx, request.(GetPingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPing")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPingResponseObject); ok {
		if err := validResponse.VisitGetPingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Register operation middleware
func (sh *strictHandler) Register(w http.ResponseWriter, r *http.Request) {
	var request RegisterRequestObject

	var body RegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Register(ctx, request.(RegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Register")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterResponseObject); ok {
		if err := validResponse.VisitRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xYzW7jNhB+FYIt0ItieVvsxae6dZsYyKJB6p4WC4OWxhI3EsklRwkMQ+9ekJRk2WK8",
	"zm/T3GQPOZyfj9/McEsTWSopQKChky3NgaWg3ec0ScCYhbwBYX8mUiAItJ9MqYInDLkU8VcjndgkOZTM",
	"fuFGAZ1Qg5qLjNZ1XUf0GtYaTP4cyuqIavhWgcHfZMrBmXopM/4wvUpLBRqb/YoZcyd1GjgxopUBLVgJ",
	"IXO8LVxDSiefu5Wk0/clarfI1VdIkDr7UzCJ5sqaRif0Gr6RlUw3ZC01iQvnigtZxg2CfoJbUDJeBH16",
	"KYeJP/LhbuvWW3+EUVIY78Q54KUVCS6yC25Q6s2DQsIRSqfoRw1rOqE/xDvEx36ZiQ9PuG4ssOFoPGFa",
	"s03IkXNAUrT7Sd6YWEdW8KkyPHl+c73aE21jRUHKdkNrU+fg49GVVtotXBpIpEhNDy5cIGQ2mRHlYYwV",
	"/Abu2eFsXSby1mN/sPUeaEbUSJEtKx1GfKUKaaltGTSoPgGwfzkJwZwhueNFQVZANGClBaRktSGx0jKt",
	"Eoy3zcd8VpPzPxbEBs1Fyp3T5NDR1n2oG8S6w9cyZejka6lLhnRC7R9nyEug0dDr78XSy9tMHsvHPXn0",
	"wu9m8yVy1pMfZ6yDzEa0u5XvGtB9ouYpbc7Z39jaHQ2dj6i3uGdGmNa5WMuWRliCvcJDywpBaWnX/prZ",
	"/0aJLFtLJvRThUAaOR3cN5clUvJESwP6lidALhaLKzK9mruasbc7osixgOA2GtFb0MZr/TAaj8b2MKlA",
	"MMXphP4yGo8+UFsUMXcpjLvrdtbQeby1EJvPaocTKMBfwn2DZ+7/Xi1Ya1kGSoM720d7nnb7OjL4U8vy",
	"8sLZo1kJ6Nqxz1tqOxxn4y6A3ijazzXqCqIjDdSXfvu0eQL9H6GFA/B1K0P4OSz3P4/HT2sQD2H0d+X6",
	"WJvyj8+uG/QtaAJaSx2STxP7Ycgdx5zYZP1kgnjIAIdwCvcVh+Cx7dHLgmWYnFBr0q2LQw3b6wRfSROI",
	"4zRNff9DuDghoNM07cxfyP/LRZzPTryH89n7v4Z1RJs5ygYrCIp/DGhiRRYHpJtjmEh3s4z9kQEStFOr",
	"KzmswhwENqYOoOPH0EFew9elN8LGl+3Q96QcHMACjGEZPLLZbdMVDV8EzropPuRYszzuvx7sHgBO27v3",
	"WuCM+/hfhmLAM6YqS2bHUJ9xyyt3sGJKWU/jsu0uG1Yf8PW0KHwH+kh27aa/l75IfU8Hk+RONE3QV7hO",
	"5mMQbxvGqXvRGNY4z82rDXEEOohWG6oDEt7X43U4BQF2bonvNUrf/nT9hqHrexOfOCmglzxl9R/B75WV",
	"v6+2bReW33NIbkgOrMCctAOEjYruvcc9pKZE/k0s2q8rTCnSaiQ5Ly2HmI1BKAd3oHsIfERh6fa+xdry",
	"hi9HG7c+tdf1vwEAAP//L9MaUS0XAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
