//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// ListeningHistoryResponse defines model for ListeningHistoryResponse.
type ListeningHistoryResponse struct {
	ListeningDate    *time.Time `json:"listening_date,omitempty"`
	MusicCover       *string    `json:"music_cover,omitempty"`
	MusicDuration    *int       `json:"music_duration,omitempty"`
	MusicId          *string    `json:"music_id,omitempty"`
	MusicLikes       *int       `json:"music_likes,omitempty"`
	MusicName        *string    `json:"music_name,omitempty"`
	SongUrl          *string    `json:"song_url,omitempty"`
	UploaderId       *string    `json:"uploader_id,omitempty"`
	UploaderUsername *string    `json:"uploader_username,omitempty"`
}

// Music defines model for Music.
type Music struct {
	DurationSeconds int     `json:"duration_seconds"`
	Id              string  `json:"id"`
	Likes           int     `json:"likes"`
	MusicCover      *string `json:"music_cover,omitempty"`
	Name            string  `json:"name"`
	SongUrl         string  `json:"song_url"`
	UploaderId      string  `json:"uploader_id"`
}

// GetListeningHistory defines model for GetListeningHistory.
type GetListeningHistory = []ListeningHistoryResponse

// GetMusic defines model for GetMusic.
type GetMusic = []Music

// GetMusicResponse defines model for GetMusicResponse.
type GetMusicResponse struct {
	DurationSeconds *int    `json:"duration_seconds,omitempty"`
	Id              *string `json:"id,omitempty"`
	Likes           *int    `json:"likes,omitempty"`
	MusicCover      *string `json:"music_cover,omitempty"`
	Name            *string `json:"name,omitempty"`
	SongUrl         *string `json:"song_url,omitempty"`
	UploaderId      *string `json:"uploader_id,omitempty"`
}

// Login defines model for Login.
type Login struct {
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// Register defines model for Register.
type Register struct {
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// DeleteFavorJSONBody defines parameters for DeleteFavor.
type DeleteFavorJSONBody struct {
	MusicID string `json:"musicID"`
}

// AddFavorJSONBody defines parameters for AddFavor.
type AddFavorJSONBody struct {
	MusicID string `json:"musicID"`
}

// DeleteListeningFromLHJSONBody defines parameters for DeleteListeningFromLH.
type DeleteListeningFromLHJSONBody struct {
	MusicId string `json:"music_id"`
}

// AddListeningToLHJSONBody defines parameters for AddListeningToLH.
type AddListeningToLHJSONBody struct {
	MusicID string `json:"musicID"`
}

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// RegisterJSONBody defines parameters for Register.
type RegisterJSONBody struct {
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// DeleteFavorJSONRequestBody defines body for DeleteFavor for application/json ContentType.
type DeleteFavorJSONRequestBody DeleteFavorJSONBody

// AddFavorJSONRequestBody defines body for AddFavor for application/json ContentType.
type AddFavorJSONRequestBody AddFavorJSONBody

// DeleteListeningFromLHJSONRequestBody defines body for DeleteListeningFromLH for application/json ContentType.
type DeleteListeningFromLHJSONRequestBody DeleteListeningFromLHJSONBody

// AddListeningToLHJSONRequestBody defines body for AddListeningToLH for application/json ContentType.
type AddListeningToLHJSONRequestBody AddListeningToLHJSONBody

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody RegisterJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (DELETE /favor/{userID})
	DeleteFavor(w http.ResponseWriter, r *http.Request, userID string)

	// (GET /favor/{userID})
	GetFavor(w http.ResponseWriter, r *http.Request, userID string)

	// (POST /favor/{userID})
	AddFavor(w http.ResponseWriter, r *http.Request, userID string)

	// (DELETE /listening-history/{userID})
	DeleteListeningFromLH(w http.ResponseWriter, r *http.Request, userID string)

	// (GET /listening-history/{userID})
	GetLH(w http.ResponseWriter, r *http.Request, userID string)

	// (POST /listening-history/{userID})
	AddListeningToLH(w http.ResponseWriter, r *http.Request, userID string)

	// (POST /login)
	Login(w http.ResponseWriter, r *http.Request)
	// Get all music
	// (GET /music)
	GetAllMusic(w http.ResponseWriter, r *http.Request)

	// (GET /music/{musicID})
	GetMusic(w http.ResponseWriter, r *http.Request, musicID string)

	// (GET /ping)
	GetPing(w http.ResponseWriter, r *http.Request)

	// (POST /register)
	Register(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DeleteFavor operation middleware
func (siw *ServerInterfaceWrapper) DeleteFavor(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID string

	err = runtime.BindStyledParameterWithOptions("simple", "userID", r.PathValue("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteFavor(w, r, userID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFavor operation middleware
func (siw *ServerInterfaceWrapper) GetFavor(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID string

	err = runtime.BindStyledParameterWithOptions("simple", "userID", r.PathValue("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFavor(w, r, userID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddFavor operation middleware
func (siw *ServerInterfaceWrapper) AddFavor(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID string

	err = runtime.BindStyledParameterWithOptions("simple", "userID", r.PathValue("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddFavor(w, r, userID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteListeningFromLH operation middleware
func (siw *ServerInterfaceWrapper) DeleteListeningFromLH(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID string

	err = runtime.BindStyledParameterWithOptions("simple", "userID", r.PathValue("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteListeningFromLH(w, r, userID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLH operation middleware
func (siw *ServerInterfaceWrapper) GetLH(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID string

	err = runtime.BindStyledParameterWithOptions("simple", "userID", r.PathValue("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLH(w, r, userID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddListeningToLH operation middleware
func (siw *ServerInterfaceWrapper) AddListeningToLH(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID string

	err = runtime.BindStyledParameterWithOptions("simple", "userID", r.PathValue("userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddListeningToLH(w, r, userID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAllMusic operation middleware
func (siw *ServerInterfaceWrapper) GetAllMusic(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAllMusic(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMusic operation middleware
func (siw *ServerInterfaceWrapper) GetMusic(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "musicID" -------------
	var musicID string

	err = runtime.BindStyledParameterWithOptions("simple", "musicID", r.PathValue("musicID"), &musicID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "musicID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMusic(w, r, musicID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPing operation middleware
func (siw *ServerInterfaceWrapper) GetPing(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPing(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("DELETE "+options.BaseURL+"/favor/{userID}", wrapper.DeleteFavor)
	m.HandleFunc("GET "+options.BaseURL+"/favor/{userID}", wrapper.GetFavor)
	m.HandleFunc("POST "+options.BaseURL+"/favor/{userID}", wrapper.AddFavor)
	m.HandleFunc("DELETE "+options.BaseURL+"/listening-history/{userID}", wrapper.DeleteListeningFromLH)
	m.HandleFunc("GET "+options.BaseURL+"/listening-history/{userID}", wrapper.GetLH)
	m.HandleFunc("POST "+options.BaseURL+"/listening-history/{userID}", wrapper.AddListeningToLH)
	m.HandleFunc("POST "+options.BaseURL+"/login", wrapper.Login)
	m.HandleFunc("GET "+options.BaseURL+"/music", wrapper.GetAllMusic)
	m.HandleFunc("GET "+options.BaseURL+"/music/{musicID}", wrapper.GetMusic)
	m.HandleFunc("GET "+options.BaseURL+"/ping", wrapper.GetPing)
	m.HandleFunc("POST "+options.BaseURL+"/register", wrapper.Register)

	return m
}

type GetListeningHistoryJSONResponse []ListeningHistoryResponse

type GetMusicJSONResponse []Music

type GetMusicResponseJSONResponse struct {
	DurationSeconds *int    `json:"duration_seconds,omitempty"`
	Id              *string `json:"id,omitempty"`
	Likes           *int    `json:"likes,omitempty"`
	MusicCover      *string `json:"music_cover,omitempty"`
	Name            *string `json:"name,omitempty"`
	SongUrl         *string `json:"song_url,omitempty"`
	UploaderId      *string `json:"uploader_id,omitempty"`
}

type DeleteFavorRequestObject struct {
	UserID string `json:"userID"`
	Body   *DeleteFavorJSONRequestBody
}

type DeleteFavorResponseObject interface {
	VisitDeleteFavorResponse(w http.ResponseWriter) error
}

type DeleteFavor200JSONResponse string

func (response DeleteFavor200JSONResponse) VisitDeleteFavorResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteFavor500JSONResponse string

func (response DeleteFavor500JSONResponse) VisitDeleteFavorResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetFavorRequestObject struct {
	UserID string `json:"userID"`
}

type GetFavorResponseObject interface {
	VisitGetFavorResponse(w http.ResponseWriter) error
}

type GetFavor200JSONResponse struct{ GetMusicJSONResponse }

func (response GetFavor200JSONResponse) VisitGetFavorResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetFavor500JSONResponse string

func (response GetFavor500JSONResponse) VisitGetFavorResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AddFavorRequestObject struct {
	UserID string `json:"userID"`
	Body   *AddFavorJSONRequestBody
}

type AddFavorResponseObject interface {
	VisitAddFavorResponse(w http.ResponseWriter) error
}

type AddFavor200JSONResponse string

func (response AddFavor200JSONResponse) VisitAddFavorResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AddFavor500JSONResponse string

func (response AddFavor500JSONResponse) VisitAddFavorResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteListeningFromLHRequestObject struct {
	UserID string `json:"userID"`
	Body   *DeleteListeningFromLHJSONRequestBody
}

type DeleteListeningFromLHResponseObject interface {
	VisitDeleteListeningFromLHResponse(w http.ResponseWriter) error
}

type DeleteListeningFromLH200JSONResponse string

func (response DeleteListeningFromLH200JSONResponse) VisitDeleteListeningFromLHResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteListeningFromLH500JSONResponse string

func (response DeleteListeningFromLH500JSONResponse) VisitDeleteListeningFromLHResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetLHRequestObject struct {
	UserID string `json:"userID"`
}

type GetLHResponseObject interface {
	VisitGetLHResponse(w http.ResponseWriter) error
}

type GetLH200JSONResponse struct {
	GetListeningHistoryJSONResponse
}

func (response GetLH200JSONResponse) VisitGetLHResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLH500JSONResponse string

func (response GetLH500JSONResponse) VisitGetLHResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AddListeningToLHRequestObject struct {
	UserID string `json:"userID"`
	Body   *AddListeningToLHJSONRequestBody
}

type AddListeningToLHResponseObject interface {
	VisitAddListeningToLHResponse(w http.ResponseWriter) error
}

type AddListeningToLH200JSONResponse string

func (response AddListeningToLH200JSONResponse) VisitAddListeningToLHResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AddListeningToLH500JSONResponse string

func (response AddListeningToLH500JSONResponse) VisitAddListeningToLHResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200ResponseHeaders struct {
	AccessToken  interface{}
	RefreshToken interface{}
}

type Login200JSONResponse struct {
	Body struct {
		Message *string `json:"message,omitempty"`
	}
	Headers Login200ResponseHeaders
}

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Access-Token", fmt.Sprint(response.Headers.AccessToken))
	w.Header().Set("Refresh-Token", fmt.Sprint(response.Headers.RefreshToken))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type Login500JSONResponse struct {
	Message *string `json:"message,omitempty"`
}

func (response Login500JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAllMusicRequestObject struct {
}

type GetAllMusicResponseObject interface {
	VisitGetAllMusicResponse(w http.ResponseWriter) error
}

type GetAllMusic200JSONResponse struct{ GetMusicJSONResponse }

func (response GetAllMusic200JSONResponse) VisitGetAllMusicResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAllMusic500JSONResponse string

func (response GetAllMusic500JSONResponse) VisitGetAllMusicResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetMusicRequestObject struct {
	MusicID string `json:"musicID"`
}

type GetMusicResponseObject interface {
	VisitGetMusicResponse(w http.ResponseWriter) error
}

type GetMusic200JSONResponse struct{ GetMusicResponseJSONResponse }

func (response GetMusic200JSONResponse) VisitGetMusicResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMusic500JSONResponse struct {
	Message *string `json:"message,omitempty"`
}

func (response GetMusic500JSONResponse) VisitGetMusicResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetPingRequestObject struct {
}

type GetPingResponseObject interface {
	VisitGetPingResponse(w http.ResponseWriter) error
}

type GetPing200JSONResponse string

func (response GetPing200JSONResponse) VisitGetPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPing500JSONResponse string

func (response GetPing500JSONResponse) VisitGetPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RegisterRequestObject struct {
	Body *RegisterJSONRequestBody
}

type RegisterResponseObject interface {
	VisitRegisterResponse(w http.ResponseWriter) error
}

type Register200JSONResponse struct {
	Message *string `json:"message,omitempty"`
}

func (response Register200JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Register500JSONResponse struct {
	Message *string `json:"message,omitempty"`
}

func (response Register500JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (DELETE /favor/{userID})
	DeleteFavor(ctx context.Context, request DeleteFavorRequestObject) (DeleteFavorResponseObject, error)

	// (GET /favor/{userID})
	GetFavor(ctx context.Context, request GetFavorRequestObject) (GetFavorResponseObject, error)

	// (POST /favor/{userID})
	AddFavor(ctx context.Context, request AddFavorRequestObject) (AddFavorResponseObject, error)

	// (DELETE /listening-history/{userID})
	DeleteListeningFromLH(ctx context.Context, request DeleteListeningFromLHRequestObject) (DeleteListeningFromLHResponseObject, error)

	// (GET /listening-history/{userID})
	GetLH(ctx context.Context, request GetLHRequestObject) (GetLHResponseObject, error)

	// (POST /listening-history/{userID})
	AddListeningToLH(ctx context.Context, request AddListeningToLHRequestObject) (AddListeningToLHResponseObject, error)

	// (POST /login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Get all music
	// (GET /music)
	GetAllMusic(ctx context.Context, request GetAllMusicRequestObject) (GetAllMusicResponseObject, error)

	// (GET /music/{musicID})
	GetMusic(ctx context.Context, request GetMusicRequestObject) (GetMusicResponseObject, error)

	// (GET /ping)
	GetPing(ctx context.Context, request GetPingRequestObject) (GetPingResponseObject, error)

	// (POST /register)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// DeleteFavor operation middleware
func (sh *strictHandler) DeleteFavor(w http.ResponseWriter, r *http.Request, userID string) {
	var request DeleteFavorRequestObject

	request.UserID = userID

	var body DeleteFavorJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteFavor(ctx, request.(DeleteFavorRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteFavor")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteFavorResponseObject); ok {
		if err := validResponse.VisitDeleteFavorResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFavor operation middleware
func (sh *strictHandler) GetFavor(w http.ResponseWriter, r *http.Request, userID string) {
	var request GetFavorRequestObject

	request.UserID = userID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetFavor(ctx, request.(GetFavorRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFavor")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetFavorResponseObject); ok {
		if err := validResponse.VisitGetFavorResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddFavor operation middleware
func (sh *strictHandler) AddFavor(w http.ResponseWriter, r *http.Request, userID string) {
	var request AddFavorRequestObject

	request.UserID = userID

	var body AddFavorJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddFavor(ctx, request.(AddFavorRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddFavor")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddFavorResponseObject); ok {
		if err := validResponse.VisitAddFavorResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteListeningFromLH operation middleware
func (sh *strictHandler) DeleteListeningFromLH(w http.ResponseWriter, r *http.Request, userID string) {
	var request DeleteListeningFromLHRequestObject

	request.UserID = userID

	var body DeleteListeningFromLHJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteListeningFromLH(ctx, request.(DeleteListeningFromLHRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteListeningFromLH")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteListeningFromLHResponseObject); ok {
		if err := validResponse.VisitDeleteListeningFromLHResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLH operation middleware
func (sh *strictHandler) GetLH(w http.ResponseWriter, r *http.Request, userID string) {
	var request GetLHRequestObject

	request.UserID = userID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLH(ctx, request.(GetLHRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLH")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLHResponseObject); ok {
		if err := validResponse.VisitGetLHResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddListeningToLH operation middleware
func (sh *strictHandler) AddListeningToLH(w http.ResponseWriter, r *http.Request, userID string) {
	var request AddListeningToLHRequestObject

	request.UserID = userID

	var body AddListeningToLHJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddListeningToLH(ctx, request.(AddListeningToLHRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddListeningToLH")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddListeningToLHResponseObject); ok {
		if err := validResponse.VisitAddListeningToLHResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAllMusic operation middleware
func (sh *strictHandler) GetAllMusic(w http.ResponseWriter, r *http.Request) {
	var request GetAllMusicRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAllMusic(ctx, request.(GetAllMusicRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAllMusic")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAllMusicResponseObject); ok {
		if err := validResponse.VisitGetAllMusicResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMusic operation middleware
func (sh *strictHandler) GetMusic(w http.ResponseWriter, r *http.Request, musicID string) {
	var request GetMusicRequestObject

	request.MusicID = musicID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMusic(ctx, request.(GetMusicRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMusic")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMusicResponseObject); ok {
		if err := validResponse.VisitGetMusicResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPing operation middleware
func (sh *strictHandler) GetPing(w http.ResponseWriter, r *http.Request) {
	var request GetPingRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPing(ctx, request.(GetPingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPing")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPingResponseObject); ok {
		if err := validResponse.VisitGetPingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Register operation middleware
func (sh *strictHandler) Register(w http.ResponseWriter, r *http.Request) {
	var request RegisterRequestObject

	var body RegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Register(ctx, request.(RegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Register")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterResponseObject); ok {
		if err := validResponse.VisitRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZX2/bNhD/KgQ3oC9KlG7oi5/mLWsSIMWCLHsqioCWzhIbiWSPpwSGoe8+kJRk2VIS",
	"51/rFHmTfeTx/vz4u9NpyRNdGq1AkeWTJc9BpID+cZokYO2FvgLlfiZaEShyj8KYQiaCpFbxV6u92CY5",
	"lMI90cIAn3BLKFXG67quI34OcwSbP4eyOuII3yqw9KdOJXhTT3UmH6bXoDaA1Ow3wtobjenIiRGvLKAS",
	"JYyZE2yRCCmffO5Wsk7fl6jdomdfISHu7U/BJiiNM41P+Dl8YzOdLthcI4sL74oPWSYtAT7BLSiFLEZ9",
	"eimHWTjy4W5j6204whqtbHDiCOjUiZRU2bG0pHHxoJBIgtIr+hVhzif8l3iF+Dgss/HmCeeNBS4cjScC",
	"USzGHDkCYkW7n+WNiXXkBJ8qK5PnNzeo3dI2URSsbDe0NnUOPh5daYV+4aWFRKvU9uAiFUHmkhlxOY6x",
	"Ql7BLTu8rZeJvg7YH2y9BZoRt1pllxWOI74yhXbUdjlqUL0FYP/xEka5IHYji4LNgCFQhQpSNluw2KBO",
	"q4TiZfNwclizo78vmAuaj5Q/p8mhp63bUDeIdYevy1SQl881loL4hLs/9kiWwKOh1/fFMsjbTN6Vj1vy",
	"GIT3ZvMlctaT381YG5mNeHcrf2pA94laprw5Z31ja3c0dD7iweKeGeO0LtVctzQiEuoVHl5WBAa1W/tH",
	"5v7bT3TZWjLhnyoC1sj54L75LLFSJqgt4LVMgB1fXJyx6dmJrxlruyNOkgoY3cYjfg1og9b3+wf7B+4w",
	"bUAJI/mE/75/sP+eu6JIuU9hPBfXGuOlg9XJYe2xAQWEi7du5KH/P/ArI83clneWeQXcHxLCepJ2iz82",
	"MiNQlEC+2/q85K6B8Sas4hPO5/1UElYQ3dEffel3R4snsLv36OTwfmi1C8fAsVnLfzs4eFr3t4mRfyvf",
	"pLp8fnh23YDXgAwQNY7Jp4l7sOxGUr6Z9wxoiBVXjO/ExxHQy4NjmI6xTqNbF3ddzPeJsdF2JHTTNN3y",
	"jk3T9O2Cvc4LVkc87hqdvaaRfggLr7rwOepypCkfJ+SuDfuIujw9fh3I2arsdyvfyPmdHcXDrUR9P3jc",
	"i+nxrlH14FV5N1hbqi0COk3TzvwL/Vou4huFb1J4O4wbB8V/FpA5kcMB6yZIQqWrKZL7kQEx0legfLMv",
	"KspBUWPqADphADjI6/h16Q0P49N23PakHGzAAqwVGTxyzNCmKxrOYve6+emYY83yuD+3XY1et9u7Nqf1",
	"xn34kaEY8IytylLgos2445UbmAljnKdx2b7XN6w+4OtpUYRedtcb4b6ngxneSjRNKFS4ThZiEC8bxql7",
	"0RjWuMDNswXzBDqIVhuqDRJe1xN0eAUj7NwS33d7S+kPbncVuqE3CYnTCnrJM07/Hfg9c/Kfq21bheWv",
	"HJIrloMoKGft6MZFBXtfQh5SU6LwNSJaryvCGNZqZLksHYfYhSUoB3eg+wTziMLS7d3F2rLDl6ONW5/a",
	"6/r/AAAA///F+887pxwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
